import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class EnrollmentCreate {
  @ApiProperty()
  student_id: number;
  @ApiProperty()
  course_id: number;
  @ApiProperty()
  enrollment_date: string;
}

export class Enrollment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  student_id: number;
  @ApiProperty()
  course_id: number;
  @ApiProperty()
  enrollment_date: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
