import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AssignmentCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  course_id: number;
  @ApiProperty()
  student_id: number;
}

export class Assignment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  course_id: number;
  @ApiProperty()
  student_id: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
